@startuml skicuplogitud
Event "1" *-- "0..N" Competitor : >
Competitor "1" *-- "0..2" Passage : >
Competitor "0..N" -- "1" Category : <
Competitor "0..N" -- "1" Profile : <
Passage "0..2" -- "1" Event : >
Category ..|> CategorizationInterface
Profile ..|> CategorizationInterface
LoaderData ..|> ExcelInterface
ExportData ..|> ExcelInterface
AlreadySetException --|> Exception
BoundaryDateException --|> Exception
BoundaryNumberException --|> Exception
EmptyStringException --|> Exception
EmailAddressSyntaxException --|> Exception
ImageExtensionException --|> Exception
NegativeNumberException --|> Exception
PastDateException --|> Exception
class Event {
    -identifier : Integer
    -name : String
    -location : String
    -beginDate : DateTimeInterfce
    -endDate : DateTimeInterface
}
class Competitor {
    -identifier : Integer
    -name : String
    -firstName : String
    -raceNumber : Integer
    -birthDate : DateTimeInterface
    -emailAdress : String
    -photo : String
}
class Category {
    -identifier : Integer
    -name : String
    -descirption : String
}
class Profile {
    -identifier : Integer
    -name : String
    -descirption : String
}
class Passage {
    -identifier : Integer
    -passageNumber : Integer
    -time : Float
}
class ArchiveResult {
    si cloture epreuve
}
class Exception
class AlreadySetException
class BoundaryDateException
class BoundaryNumberException
class EmptyStringException
class EmailAddressSyntaxException
class ImageExtensionException
class NegativeNumberException
class PastDateException
class LoaderData
class ExportData
interface ExcelInterface
interface CategorizationInterface
@enduml
