@startuml skicuplogitud
Contest "1" *-- "0..N" Competitor : >
Competitor "1" *-- "0..2" Stopwatch : >
Competitor "0..N" -- "1" Category : <
Competitor "0..N" -- "0..1" Profile : <
Stopwatch "0..2" -- "1" Contest : >
Category ..|> CategorizationInterface
Profile ..|> CategorizationInterface
LoaderData ..|> ExcelInterface
ExportData ..|> ExcelInterface
AlreadySetException --|> Exception
BoundaryDateException --|> Exception
BoundaryNumberException --|> Exception
EmptyStringException --|> Exception
EmailAddressSyntaxException --|> Exception
ImageExtensionException --|> Exception
NegativeNumberException --|> Exception
PastDateException --|> Exception
class Contest {
    -identifier : Integer
    -name : String < 150
    -location : String < 150
    -beginDate : DateTimeInterfce
    -endDate : DateTimeInterface
}
class Competitor {
    -identifier : Integer
    -name : String < 150
    -firstName : String < 150
    -raceNumber : Integer
    -birthDate : DateTimeInterface
    -emailAdress : String < 100
    -photo : String|Null < 255
}
class Category {
    -identifier : Integer
    -name : String < 150
    -descirption : String|Null < 500
}
class Profile {
    -identifier : Integer
    -name : String < 150
    -descirption : String|Null < 500
}
class Stopwatch {
    -identifier : Integer
    -turn : Integer
    -time : Float
}
class ArchiveResult {
    si cloture epreuve
}
class Exception
class AlreadySetException
class BoundaryDateException
class BoundaryNumberException
class EmptyStringException
class EmailAddressSyntaxException
class ImageExtensionException
class NegativeNumberException
class PastDateException
class LoaderData
class ExportData
interface ExcelInterface
interface CategorizationInterface
@enduml
